### ISSUE TITLE
More resilient and reliable streaming

### ISSUE THREAD

**Issue by autodidaddict** [wascc/fs-provider#1]
The initial 0.0.1 first commit version of this provider assumes that the stream of blocks coming from the actor will be received in sequential order. We don't necessarily know that will always be true, and so we should support more use cases:

* Receiving chunks out of order via calls to `upload_chunk` in the actor SDK
* Ignoring duplicate chunks
* Purging a file and logging appropriate error to stdout when the provider never receives all of the expected chunks

**Comment by andrisak** [comment]
The PR just handles the first two cases in-memory. Reading the 3rd point again, it seems like it maybe should be more robust and persist each chunk and combine them when the final chunk arrives?

**Comment by autodidaddict** [comment]
Thinking back to the old version of me that wrote this, I was thinking about the scenario where an upload is started for, say, `20` blocks, and the system only ever receives `18` blocks and never reaches the condition where it considers the file transfer complete. I'm thinking maybe it's safer to create another issue that will solve that problem by creating a timer/thread that goes through and periodically purges incomplete transfers.

**Comment by andrisak** [comment]
Sounds good. Are there any adjustments you'd like to see in the PR? The test is not very pretty, do you have any thoughts about how to test this provider?

**Comment by autodidaddict** [comment]
I think the only two things I'd like to see are this branch incorporating the latest sanitization code from master, and maybe upgrade the test so that it verifies that everything works properly when the total number of bytes is not evenly divisible by the chunk size (which results in there being a "leftover" small chunk at the end)
