### ISSUE TITLE
[security] sanitize path input from the guest

### ISSUE THREAD

**Issue by bacongobbler** [wascc/fs-provider#2]
If I provide a path like `//foo.txt` as the blob ID to `get_object_info`, `blob_to_path` will short-trip to the root directory of the host, resulting in retrieving file info the host probably didn't want to expose to the runtime.

The container name and blob ID should always be evaluated from the context of `rootdir`. For example, if `rootdir` is `/tmp`, the container name is `foo`, and the blob ID is `//etc/shadow`, the resultant filepath should be `/tmp/etc/shadow` rather than `/etc/shadow`.

**Comment by bacongobbler** [comment]
Thinking about this a little more, the above example should probably evaluate to `/tmp/foo/etc/shadow`, such that the blob ID is relative to the root of the container.

**Comment by autodidaddict** [comment]
Good catch. Will address this Monday
